# Generated by Django 5.1 on 2024-11-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=100)),
                ('discount_offer', models.CharField(choices=[('50%', '50% discount'), ('25%', '25% discount'), ('10%', '10% discount')], max_length=20)),
                ('ticket_number', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('Nairobi', 'Nairobi'), ('Garissa', 'Garissa'), ('Wajir', 'Wajir')], max_length=20)),
                ('date_processed', models.DateField()),
            ],
        ),
    ]
