# Generated by Django 5.1 on 2024-11-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountoffer',
            name='account_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='discountoffer',
            name='discount_offer',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='discountoffer',
            name='region',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='discountoffer',
            name='ticket_number',
            field=models.CharField(max_length=10),
        ),
    ]
